import random

def text_to_list(file_path):
    with open(file_path, 'r') as file: 
        quiz_list = file.readlines() # separates lines based on newline characters and store them into a list

    quiz_list = [trailspace.strip() for trailspace in quiz_list] # removes any leading or trailing whitespaces
    return quiz_list

file_path = 'random-module/hard_high_school_math_quiz.txt'  # generated by https://chatgpt.com/
textlist = text_to_list(file_path)    # it is the list created on the text file

def random_questionAnswerPair(textlist):

    random_question = random.choice(range(0,len(textlist), 2)) # randomly select an element(odd indexed) from the list 

    question = textlist[random_question]
    correct_answer = textlist[random_question + 1] # the correct answer is in the next element of the respective question
    print(question)
    return correct_answer # function returns the correct answer of the randomy selected question

n = 1
score = 0
while (n <= 5):
    correct_answer = random_questionAnswerPair(textlist) # gets the value from the "random_questionAnswerPair" fn
    user_answer = input("Your answer: ").strip() 
    if user_answer.lower() == correct_answer.lower():
        score += 1
    else:
        print(f"Incorrect. The correct answer is: {correct_answer}\n")
    
    n += 1
print(f'\n\nYour score is {score}/5')